#Inspired by this tweet: https://twitter.com/Pennacchiiiii/status/1299245042662617088

import random

column1 = []
column2 = []
column3 = []

column1.append("artless")
column1.append("bawdy")
column1.append("beslubbering")
column1.append("bootless")
column1.append("churlish")
column1.append("cockered")
column1.append("clouted")
column1.append("craven")
column1.append("currish")
column1.append("dankish")
column1.append("dissembling")
column1.append("droning")
column1.append("errant")
column1.append("fawning")
column1.append("fobbing")
column1.append("froward")
column1.append("frothy")
column1.append("gleeking")
column1.append("goatish")
column1.append("gorbellied")
column1.append("impertinent")
column1.append("infectious")
column1.append("jarring")
column1.append("loggerheaded")
column1.append("lumpish")
column1.append("mammering")
column1.append("mangled")
column1.append("mewling")
column1.append("paunchy")
column1.append("pribbling")
column1.append("puking")
column1.append("puny")
column1.append("qualling")
column1.append("rank")
column1.append("reeky")
column1.append("roguish")
column1.append("ruttish")
column1.append("saucy")
column1.append("spleeny")
column1.append("spongy")
column1.append("surly")
column1.append("tottering")
column1.append("unmuzzled")
column1.append("vain")
column1.append("venomed")
column1.append("villainous")
column1.append("warped")
column1.append("wayward")
column1.append("weedy")
column1.append("yeasty")

column2.append("base-court")
column2.append("bat-fowling")
column2.append("beef-witted")
column2.append("beetle-headed")
column2.append("boil-brained")
column2.append("clapper-clawed")
column2.append("clay-brained")
column2.append("common-kissing")
column2.append("crook-pated")
column2.append("dismal-dreaming")
column2.append("dizzy-eyed")
column2.append("doghearted")
column2.append("dread-bolted")
column2.append("earth-vexing")
column2.append("elf-skinned")
column2.append("fat-kidneyed")
column2.append("fen-sucked")
column2.append("flap-mouthed")
column2.append("fly-bitten")
column2.append("folly-fallen")
column2.append("fool-born")
column2.append("full-gorged")
column2.append("guts-griping")
column2.append("half-faced")
column2.append("hasty-witted")
column2.append("hedge-born")
column2.append("hell-hated")
column2.append("idle-headed")
column2.append("ill-breeding")
column2.append("ill-nurtured")
column2.append("knotty-pated")
column2.append("milk-livered")
column2.append("motley-minded")
column2.append("onion-eyed")
column2.append("plume-plucked")
column2.append("pottle-deep")
column2.append("pox-marked")
column2.append("reeling-ripe")
column2.append("rough-hewn")
column2.append("rude-growing")
column2.append("rump-fed")
column2.append("shard-borne")
column2.append("sheep-biting")
column2.append("spur-galled")
column2.append("swag-bellied")
column2.append("tardy-gaited")
column2.append("tickle-brained")
column2.append("toad-spotted")
column2.append("unchin-snouted")
column2.append("weather-bitten")

column3.append("apple-john")
column3.append("baggage")
column3.append("barnacle")
column3.append("bladder")
column3.append("boar-pig")
column3.append("bugbear")
column3.append("bum-bailey")
column3.append("canker-blossom")
column3.append("clack-dish")
column3.append("clotpole")
column3.append("coxcomb")
column3.append("codpiece")
column3.append("death-token")
column3.append("dewberry")
column3.append("flap-dragon")
column3.append("flax-wench")
column3.append("flirt-gill")
column3.append("foot-licker")
column3.append("fustilarian")
column3.append("giglet")
column3.append("gudgeon")
column3.append("haggard")
column3.append("harpy")
column3.append("hedge-pig")
column3.append("horn-beast")
column3.append("hugger-mugger")
column3.append("joithead")
column3.append("lewdster")
column3.append("lout")
column3.append("maggot-pie")
column3.append("malt-worm")
column3.append("mammet")
column3.append("measle")
column3.append("minnow")
column3.append("miscreant")
column3.append("moldwarp")
column3.append("mumble-news")
column3.append("nut-hook")
column3.append("pigeon-egg")
column3.append("pignut")
column3.append("puttock")
column3.append("pumpion")
column3.append("ratsbane")
column3.append("scut")
column3.append("skainsmate")
column3.append("strumpet")
column3.append("varlot")
column3.append("vassal")
column3.append("whey-face")
column3.append("wagtail")

r1 = random.randint(0, 49)
r2 = random.randint(0, 49)
r3 = random.randint(0, 49)

insult = "Thou " + column1[r1] + " " + column2[r2] + " " + column3[r3]

print(str(r1) + " " + str(r2) + " " + str(r3))
print("")
print(insult)
print("")
print("Thank you @Pennacchiiiii - https://twitter.com/Pennacchiiiii" )
